SDAPSDB  :=db
SDAPS    :=sdaps
FLOW     := /home/sikshana/sas/flow
VERIFY   := $(FLOW)/bin/csvverify.py
GS       :=gs
GSOPTS   := -q -dNOPAUSE -dBATCH -r300 -sDEVICE=tiffg4 -sPAPERSIZE=a4
TOPDIR   :=.
PDF      := $(wildcard $(TOPDIR)/*/*/*/*stamp.pdf)
DIRS     := $(dir $(PDF))
TIFF     := $(patsubst %.pdf, %.tif, $(PDF))
DB       := $(addsuffix .db, $(DIRS))
REC      := $(addsuffix .rec, $(DIRS))
CSV      := $(addsuffix .csv, $(DIRS))
VER      := $(addsuffix .ver, $(DIRS))

default: $(VER)

# define dependencies for individual
# survey id runs.
define make-tiff-targets
target=$(addsuffix .db, $(dir $1))
prereq:=$1
$${target}: $${prereq}
	$(SDAPS) $(dir $1)db add $$<
	echo "Foo"
	echo $$@
	echo $1
	echo $$<
endef

$(foreach tif,$(TIFF),$(eval $(call make-tiff-targets,$(tif))))

%.tif: %.pdf
	$(GS) $(GSOPTS) -sOutputFile=$@ $<

%.rec: %.db
	$(SDAPS) $(dir $@)db recognize
	@touch $@

%.csv: %.rec
	$(SDAPS) $(dir $@)db csv export
	@touch $@

%.ver: %.csv
	$(VERIFY) --rundir $(dir $@)
	touch $@
.SECONDARY:
